apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoria-metrics
  namespace: argocd
spec:
  project: default

  sources:
    - repoURL: https://victoriametrics.github.io/helm-charts/
      chart: victoria-metrics-k8s-stack
      targetRevision: "0.72.4"
      helm:
        releaseName: vm-stack
        valueFiles:
          - $values/k8s/monitoring/values.yaml

    - repoURL: https://github.com/DenysMelnychenko/devops-learning.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  ignoreDifferences:
    # Secret з TLS сертифікатом генерується автоматично оператором
    # при кожному запуску — його немає в git, тому завжди OutOfSync
    # Рішення: ігноруємо поле /data (весь вміст секрету)
    - group: ""
      kind: Secret
      name: vm-stack-victoria-metrics-operator-validation
      namespace: monitoring
      jsonPointers:
        - /data

    # ValidatingWebhookConfiguration теж містить auto-generated CA cert
    # /webhooks/0/clientConfig/caBundle — поле з сертифікатом
    # 0 — індекс першого webhook в масиві
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      name: vm-stack-victoria-metrics-operator-admission
      jsonPointers:
        - /webhooks/0/clientConfig/caBundle